[colors.primary]
background = '#f3ead3'
foreground = '#5c6a72'

[colors.normal]
black   = '#5c6a72'
red     = '#f85552'
green   = '#8da101'
yellow  = '#dfa000'
blue    = '#3a94c5'
magenta = '#df69ba'
cyan    = '#35a77c'
white   = '#d8d3ba'

[colors.bright]
black   = '#5c6a72'
red     = '#f85552'
green   = '#8da101'
yellow  = '#dfa000'
blue    = '#3a94c5'
magenta = '#df69ba'
cyan    = '#35a77c'
white   = '#d8d3ba'

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 11.0

[font.bold]
family = "iosevka"
style = "Bold"

[font.bold_italic]
family = "iosevka"
style = "Bold Italic"

[font.italic]
family = "iosevka"
style = "Italic"

[font.normal]
family = "iosevka"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Shift|Control"

[scrolling]
history = 100000
multiplier = 3

[window]
opacity = 1.0

[general]
live_config_reload = true
